server:
  port: 8077
spring:
  application:
    name: config-server
  profiles:
    active: vault
  cloud:
    config:
      discovery:
        enabled: true
      server:
        vault:
          kv-version: 2
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka